[package]
name = "quark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trace = {version = "0.1.7", optional = true, default-features = false}
log = "0.4"
env_logger = "0.11"